// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/tor.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiTorInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 333622112;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_tor',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  TorClientWrapper crateApiTorTorInstanceAutoAccessorGetClient(
      {required TorInstance that});

  TorProxyHandle crateApiTorTorInstanceAutoAccessorGetProxy(
      {required TorInstance that});

  int crateApiTorTorInstanceAutoAccessorGetSocksPort(
      {required TorInstance that});

  void crateApiTorTorInstanceAutoAccessorSetClient(
      {required TorInstance that, required TorClientWrapper client});

  void crateApiTorTorInstanceAutoAccessorSetProxy(
      {required TorInstance that, required TorProxyHandle proxy});

  void crateApiTorTorInstanceAutoAccessorSetSocksPort(
      {required TorInstance that, required int socksPort});

  Future<void> crateApiTorBootstrap({required TorClientWrapper client});

  Future<BigInt> crateApiTorGetNofileLimit();

  Future<void> crateApiTorHello();

  Future<void> crateApiTorInitApp();

  Future<void> crateApiTorSetDormant(
      {required TorClientWrapper client, required bool softMode});

  Future<BigInt> crateApiTorSetNofileLimit({required BigInt limit});

  Future<TorInstance> crateApiTorStartTor(
      {required int socksPort,
      required String stateDir,
      required String cacheDir});

  Future<void> crateApiTorStopProxy({required TorProxyHandle proxy});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TorClientWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TorClientWrapper;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_TorClientWrapperPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TorInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TorInstance;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_TorInstancePtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TorProxyHandle;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TorProxyHandle;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_TorProxyHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  TorClientWrapper crateApiTorTorInstanceAutoAccessorGetClient(
      {required TorInstance that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorTorInstanceAutoAccessorGetClientConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorTorInstanceAutoAccessorGetClientConstMeta =>
      const TaskConstMeta(
        debugName: "TorInstance_auto_accessor_get_client",
        argNames: ["that"],
      );

  @override
  TorProxyHandle crateApiTorTorInstanceAutoAccessorGetProxy(
      {required TorInstance that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorTorInstanceAutoAccessorGetProxyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorTorInstanceAutoAccessorGetProxyConstMeta =>
      const TaskConstMeta(
        debugName: "TorInstance_auto_accessor_get_proxy",
        argNames: ["that"],
      );

  @override
  int crateApiTorTorInstanceAutoAccessorGetSocksPort(
      {required TorInstance that}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
            that, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_16,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorTorInstanceAutoAccessorGetSocksPortConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorTorInstanceAutoAccessorGetSocksPortConstMeta =>
      const TaskConstMeta(
        debugName: "TorInstance_auto_accessor_get_socks_port",
        argNames: ["that"],
      );

  @override
  void crateApiTorTorInstanceAutoAccessorSetClient(
      {required TorInstance that, required TorClientWrapper client}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
            that, serializer);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
            client, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorTorInstanceAutoAccessorSetClientConstMeta,
      argValues: [that, client],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorTorInstanceAutoAccessorSetClientConstMeta =>
      const TaskConstMeta(
        debugName: "TorInstance_auto_accessor_set_client",
        argNames: ["that", "client"],
      );

  @override
  void crateApiTorTorInstanceAutoAccessorSetProxy(
      {required TorInstance that, required TorProxyHandle proxy}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
            that, serializer);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
            proxy, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorTorInstanceAutoAccessorSetProxyConstMeta,
      argValues: [that, proxy],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorTorInstanceAutoAccessorSetProxyConstMeta =>
      const TaskConstMeta(
        debugName: "TorInstance_auto_accessor_set_proxy",
        argNames: ["that", "proxy"],
      );

  @override
  void crateApiTorTorInstanceAutoAccessorSetSocksPort(
      {required TorInstance that, required int socksPort}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
            that, serializer);
        sse_encode_u_16(socksPort, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorTorInstanceAutoAccessorSetSocksPortConstMeta,
      argValues: [that, socksPort],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorTorInstanceAutoAccessorSetSocksPortConstMeta =>
      const TaskConstMeta(
        debugName: "TorInstance_auto_accessor_set_socks_port",
        argNames: ["that", "socksPort"],
      );

  @override
  Future<void> crateApiTorBootstrap({required TorClientWrapper client}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
            client, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_tor_error,
      ),
      constMeta: kCrateApiTorBootstrapConstMeta,
      argValues: [client],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorBootstrapConstMeta => const TaskConstMeta(
        debugName: "bootstrap",
        argNames: ["client"],
      );

  @override
  Future<BigInt> crateApiTorGetNofileLimit() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_tor_error,
      ),
      constMeta: kCrateApiTorGetNofileLimitConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorGetNofileLimitConstMeta => const TaskConstMeta(
        debugName: "get_nofile_limit",
        argNames: [],
      );

  @override
  Future<void> crateApiTorHello() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorHelloConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorHelloConstMeta => const TaskConstMeta(
        debugName: "hello",
        argNames: [],
      );

  @override
  Future<void> crateApiTorInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiTorSetDormant(
      {required TorClientWrapper client, required bool softMode}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
            client, serializer);
        sse_encode_bool(softMode, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTorSetDormantConstMeta,
      argValues: [client, softMode],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorSetDormantConstMeta => const TaskConstMeta(
        debugName: "set_dormant",
        argNames: ["client", "softMode"],
      );

  @override
  Future<BigInt> crateApiTorSetNofileLimit({required BigInt limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_64(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_u_64,
        decodeErrorData: sse_decode_tor_error,
      ),
      constMeta: kCrateApiTorSetNofileLimitConstMeta,
      argValues: [limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorSetNofileLimitConstMeta => const TaskConstMeta(
        debugName: "set_nofile_limit",
        argNames: ["limit"],
      );

  @override
  Future<TorInstance> crateApiTorStartTor(
      {required int socksPort,
      required String stateDir,
      required String cacheDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_16(socksPort, serializer);
        sse_encode_String(stateDir, serializer);
        sse_encode_String(cacheDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance,
        decodeErrorData: sse_decode_tor_error,
      ),
      constMeta: kCrateApiTorStartTorConstMeta,
      argValues: [socksPort, stateDir, cacheDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorStartTorConstMeta => const TaskConstMeta(
        debugName: "start_tor",
        argNames: ["socksPort", "stateDir", "cacheDir"],
      );

  @override
  Future<void> crateApiTorStopProxy({required TorProxyHandle proxy}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
            proxy, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_tor_error,
      ),
      constMeta: kCrateApiTorStopProxyConstMeta,
      argValues: [proxy],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTorStopProxyConstMeta => const TaskConstMeta(
        debugName: "stop_proxy",
        argNames: ["proxy"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TorClientWrapper => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TorClientWrapper => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TorInstance => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TorInstance => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_TorProxyHandle => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_TorProxyHandle => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle;

  @protected
  TorClientWrapper
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorClientWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorInstance
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorProxyHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorProxyHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorInstance
      dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorClientWrapper
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorClientWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorInstance
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorClientWrapper
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorClientWrapperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorInstance
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorInstanceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  TorProxyHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TorProxyHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  TorError dco_decode_tor_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return TorError_BootstrapError(
          dco_decode_String(raw[1]),
        );
      case 1:
        return TorError_ProxyStartError(
          dco_decode_String(raw[1]),
        );
      case 2:
        return TorError_ProxyStopError(
          dco_decode_String(raw[1]),
        );
      case 3:
        return TorError_ClientNotInitialized();
      case 4:
        return TorError_RuntimeError(
          dco_decode_String(raw[1]),
        );
      case 5:
        return TorError_ConfigError(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  TorClientWrapper
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorClientWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorInstance
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorProxyHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorProxyHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorInstance
      sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorClientWrapper
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorClientWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorInstance
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorClientWrapper
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorClientWrapperImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorInstance
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorInstanceImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  TorProxyHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return TorProxyHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  TorError sse_decode_tor_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return TorError_BootstrapError(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return TorError_ProxyStartError(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return TorError_ProxyStopError(var_field0);
      case 3:
        return TorError_ClientNotInitialized();
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return TorError_RuntimeError(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return TorError_ConfigError(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          TorClientWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorClientWrapperImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          TorInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorInstanceImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
          TorProxyHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorProxyHandleImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          TorInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorInstanceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          TorClientWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorClientWrapperImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          TorInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorInstanceImpl).frbInternalSseEncode(move: false),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorClientWrapper(
          TorClientWrapper self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorClientWrapperImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorInstance(
          TorInstance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorInstanceImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTorProxyHandle(
          TorProxyHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as TorProxyHandleImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_tor_error(TorError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case TorError_BootstrapError(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case TorError_ProxyStartError(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case TorError_ProxyStopError(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case TorError_ClientNotInitialized():
        sse_encode_i_32(3, serializer);
      case TorError_RuntimeError(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case TorError_ConfigError(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class TorClientWrapperImpl extends RustOpaque implements TorClientWrapper {
  // Not to be used by end users
  TorClientWrapperImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TorClientWrapperImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TorClientWrapper,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TorClientWrapper,
    rustArcDecrementStrongCountPtr: RustLib
        .instance.api.rust_arc_decrement_strong_count_TorClientWrapperPtr,
  );
}

@sealed
class TorInstanceImpl extends RustOpaque implements TorInstance {
  // Not to be used by end users
  TorInstanceImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TorInstanceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TorInstance,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TorInstance,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TorInstancePtr,
  );

  TorClientWrapper get client =>
      RustLib.instance.api.crateApiTorTorInstanceAutoAccessorGetClient(
        that: this,
      );

  TorProxyHandle get proxy =>
      RustLib.instance.api.crateApiTorTorInstanceAutoAccessorGetProxy(
        that: this,
      );

  int get socksPort =>
      RustLib.instance.api.crateApiTorTorInstanceAutoAccessorGetSocksPort(
        that: this,
      );

  set client(TorClientWrapper client) => RustLib.instance.api
      .crateApiTorTorInstanceAutoAccessorSetClient(that: this, client: client);

  set proxy(TorProxyHandle proxy) => RustLib.instance.api
      .crateApiTorTorInstanceAutoAccessorSetProxy(that: this, proxy: proxy);

  set socksPort(int socksPort) =>
      RustLib.instance.api.crateApiTorTorInstanceAutoAccessorSetSocksPort(
          that: this, socksPort: socksPort);
}

@sealed
class TorProxyHandleImpl extends RustOpaque implements TorProxyHandle {
  // Not to be used by end users
  TorProxyHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  TorProxyHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_TorProxyHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_TorProxyHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_TorProxyHandlePtr,
  );
}
