// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'tor.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `start_proxy_internal`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RUNTIME`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `deref`, `fmt`, `fmt`, `initialize`

/// Start Tor client and proxy
///
/// This is a blocking operation that may take several seconds.
/// It bootstraps the Tor network connection and starts a SOCKS proxy.
Future<TorInstance> startTor(
        {required int socksPort,
        required String stateDir,
        required String cacheDir}) =>
    RustLib.instance.api.crateApiTorStartTor(
        socksPort: socksPort, stateDir: stateDir, cacheDir: cacheDir);

/// Re-bootstrap the Tor client
///
/// Call this after network changes or to refresh the connection.
Future<void> bootstrap({required TorClientWrapper client}) =>
    RustLib.instance.api.crateApiTorBootstrap(client: client);

/// Set the client dormant mode
///
/// * `soft_mode` - If true, uses Soft dormant mode (keeps some circuits warm)
///                 If false, uses Normal mode (full operation)
Future<void> setDormant(
        {required TorClientWrapper client, required bool softMode}) =>
    RustLib.instance.api
        .crateApiTorSetDormant(client: client, softMode: softMode);

/// Stop the Tor proxy
///
/// This safely aborts the proxy task. Previously this could panic
/// and crash the app - with FRB, any panic becomes a catchable exception.
Future<void> stopProxy({required TorProxyHandle proxy}) =>
    RustLib.instance.api.crateApiTorStopProxy(proxy: proxy);

/// Test function to verify library linking
Future<void> hello() => RustLib.instance.api.crateApiTorHello();

Future<BigInt> getNofileLimit() =>
    RustLib.instance.api.crateApiTorGetNofileLimit();

Future<BigInt> setNofileLimit({required BigInt limit}) =>
    RustLib.instance.api.crateApiTorSetNofileLimit(limit: limit);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TorClientWrapper>>
abstract class TorClientWrapper implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TorInstance>>
abstract class TorInstance implements RustOpaqueInterface {
  TorClientWrapper get client;

  TorProxyHandle get proxy;

  int get socksPort;

  set client(TorClientWrapper client);

  set proxy(TorProxyHandle proxy);

  set socksPort(int socksPort);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TorProxyHandle>>
abstract class TorProxyHandle implements RustOpaqueInterface {}

@freezed
sealed class TorError with _$TorError implements FrbException {
  const TorError._();

  const factory TorError.bootstrapError(
    String field0,
  ) = TorError_BootstrapError;
  const factory TorError.proxyStartError(
    String field0,
  ) = TorError_ProxyStartError;
  const factory TorError.proxyStopError(
    String field0,
  ) = TorError_ProxyStopError;
  const factory TorError.clientNotInitialized() = TorError_ClientNotInitialized;
  const factory TorError.runtimeError(
    String field0,
  ) = TorError_RuntimeError;
  const factory TorError.configError(
    String field0,
  ) = TorError_ConfigError;
}
